---
- name: Setup .bash_profile
  template:
    src: bash_profile.j2
    dest: /home/ec2-user/.bash_profile

- name: Enable EPEL repository     #epel repositoryを有効にする
  command: amazon-linux-extras install epel -y
  become: yes

- name: Install required packages
  yum:
    name: 
      - git 
      - gcc
      - gcc-c++
      - make
      - glibc-headers
      - openssl-devel
      - readline-devel
      - libyaml-devel
      - zlib-devel
      - libffi-devel
      - libxml2-devel
      - libxslt-devel
      - sqlite-devel
      - ImageMagick-devel
      - ImageMagick
    state: present
    enablerepo: epel
  become: yes

- name: 'Check if the application directory exists'
  stat:
    path: "{{ app_dir }}"
  register: sample_app

- name: 'Clone the repository'
  git:
    repo: 'https://github.com/yuta-ushijima/raisetech-live8-sample-app.git'
    dest: "{{ app_dir }}"
  when: not sample_app.stat.exists

