---
- name: Set development.rb from template
  template:
    src: development.rb.j2
    dest: "{{ app_dir }}/config/environments/development.rb"
  ignore_errors: yes  #dry run用

- name: Set storage.yml from template
  template:
    src: storage.yml.j2
    dest: "{{ app_dir }}/config/storage.yml"
  ignore_errors: yes  #dry run用

# libvips
- name: Download libvips source code
  get_url:
    url: https://github.com/libvips/libvips/releases/download/v8.12.2/vips-8.12.2.tar.gz
    dest: /tmp/vips-8.12.2.tar.gz
    become: yes

- name: Extract libvips
  unarchive:
    src: /tmp/vips-8.12.2.tar.gz
    dest: /tmp/
    remote_src: yes
    become: yes

- name: Build and install libvips
  shell: |
    cd /tmp/vips-8.12.2
    ./configure
    make
    make install
  args:
    creates: /usr/local/bin/vips
    become: yes

# 実行準備
- name: Initialize rbenv and run bundle install
  shell: bash -lc "eval '$(rbenv init -)'; bundle install"
  args:
    chdir: "{{ app_dir }}"

- name: Run db:create
  shell: bash -lc "rails db:create"
  args:
    chdir: "{{ app_dir }}"

- name: Run db:migrate
  shell: bash -lc "rails db:migrate"
  args:
    chdir: "{{ app_dir }}"


- name: Asset precompile
  shell: bash -lc "rails assets:precompile"
  args: 
    chdir: "{{ app_dir }}"
  async: 600
  poll: 0

- name: Run bin/setup
  shell: bash -lc "bin/setup"
  args: 
    chdir: "{{ app_dir }}"
