---
- name: Check if Yarn is installed
  shell: bash -lc "yarn -v"
  register: yarn_installed
  changed_when: no
  ignore_errors: yes

- name: Install Yarn using curl and bash
  shell: |
    curl -o- -L https://yarnpkg.com/install.sh | bash
    source ~/.bashrc
  args:
    executable: /bin/bash
  become: yes
  become_user: ec2-user
  when: yarn_installed is failed

