---
- name: Check if Yarn is installed
  shell: bash -lc "yarn -v"
  register: yarn_installed
  changed_when: no
  ignore_errors: yes

- name: Source .bash_profile
  shell: source ~/.bash_profile
  become: yes
  become_user: ec2-user

- name: Install Yarn using curl and bash
  shell: |
    export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version {{ yarn_version }}
  become: yes
  become_user: ec2-user
  when: yarn_installed is failed
  ignore_errors: yes
