---
- name: Check if Yarn is installed
  shell: bash -lc "yarn -v"
  register: yarn_installed
  changed_when: no
  ignore_errors: yes

- name: Install Yarn using curl and bash
  shell: |
    export PATH=$PATH:/home/ec2-user/.nvm/versions/node/v17.9.1/bin
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version {{ yarn_version }}
  args:
    executable: /bin/bash
  when: yarn_installed is failed
  become_user: ec2-user


