---
- name: Check if Yarn is installed
  shell: bash -lc "yarn -v"
  register: yarn_installed
  ignore_errors: yes

- name: Yarn install
  shell: bash -lc "npm install --global yarn@1.22.19"
  ignore_errors: yes
  when: yarn_installed is failed

- name: Ensure /etc/profile.d/yarn.sh exists
  file:
    path: /etc/profile.d/yarn.sh
    state: touch
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Add Yarn to /etc/profile.d/yarn.sh
  blockinfile:
    path: /etc/profile.d/yarn.sh
    block: |
      export PATH="$PATH:$(yarn global bin)"
  when: yarn_installed.rc == 0
  become: yes



