---   
- name: Remove MariaDB packages
  yum:
    name: mariadb-server
    state: absent

- name: Install MySQL development package
  yum:
    name: mysql-devel
    state: present
  become: yes

- name: Install MySQL client
  yum:
    name: mysql
    state: present
  become: yes

- name: Set database.yml from template
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
  become: yes

- name: Set my.cnf from template
  become: yes
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: '0755'

