---
- name: Check if nginx is installed
  command: bash -lc "nginx -v"
  register: nginx_installed
  ignore_errors: yes

- name: Update yum cache
  yum:
    update_cache: yes
  become: yes

- name: Ensure ec2-user is in the nginx group
  user:
    name: ec2-user
    groups: nginx
    append: yes
  become: yes

- name: Install Nginx
  yum:
    name: nginx
    state: present
  become: yes
  when: nginx_installed is failed

- name: Change ownership
  file:
    path: /var/lib/nginx
    owner: ec2-user
    group: ec2-user
    mode: '770'
  become: yes

- name: Change ownership log
  file:
    path: /var/log/nginx
    owner: ec2-user
    group: nginx
    mode: '750'
  become: yes

- name: Set nginx.conf from template
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: yes
  ignore_errors: yes  #dry run用

- name: Restart puma
  service:
    name: puma
    state: restarted
  become: yes


- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes



