---
- name: Check if NVM is installed
  command: bash -lc "command -v nvm"
  register: nvm_installed
  ignore_errors: yes

- name: Install NVM if not installed
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  args:
    creates: /home/ec2-user/.nvm/nvm.sh
  become_user: ec2-user
  when: nvm_installed.rc == 0

- name: Set nvm.sh from template
  template:
    src: nvm.sh.j2
    dest: "/etc/profile.d/nvm.sh"
    owner: root
    group: root
    mode: 0755

- name: NVM is installed
  command: bash -lc "nvm install {{ node_version }}"
  when: nvm_installed.rc == 0

- name: NVM use version
  command: bash -lc "nvm use {{ node_version }}"







