---
- name: Check if NVM is installed
  command: bash -lc "command -v nvm"
  register: nvm_installed
  ignore_errors: yes

- name: Install NVM if not installed
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  args:
    creates: /home/ec2-user/.nvm/nvm.sh
  become_user: ec2-user

- name: Ensure /etc/profile.d/nvm.sh exists
  file:
    path: /etc/profile.d/nvm.sh
    state: touch
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Add NVM to /etc/profile.d
  blockinfile:
    path: /etc/profile.d/nvm.sh
    block: |
      export NVM_DIR="/home/ec2-user/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  when: nvm_installed.rc == 0
  become: yes 

- name: NVM is installed
  command: bash -lc "nvm install {{ node_version }}"
  when: nvm_installed.rc == 0

- name: NVM use version
  command: bash -lc "nvm use {{ node_version }}"







