---
- name: Check if rbenv is installed
  shell: rbenv -v
  register: rbenv_installed
  ignore_errors: yes

- name: Clone rbenv if not installed
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/home/ec2-user/.rbenv'
  when: rbenv_installed is failed

- name: Ensure /etc/profile.d/rbenv.sh exists
  file:
    path: /etc/profile.d/rbenv.sh
    state: touch
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Add rbenv initialization to rbenv.sh
  blockinfile:
    path: /etc/profile.d/rbenv.sh
    block: |
      export RBENV_ROOT="/home/ec2-user/.rbenv"
      export PATH="${RBENV_ROOT}/bin:${PATH}"
      eval "$(rbenv init -)"
  when: rbenv_installed is failed
  become: yes 

- name: Clone ruby-build if not installed
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/home/ec2-user/.rbenv/plugins/ruby-build'
  when: rbenv_installed is failed

- name: Reload shell profile
  shell: "source /etc/profile"
  become: yes
  when: rbenv_installed is failed

- name: Check if Ruby is already installed
  shell: rbenv versions | grep {{ ruby_version }}
  register: ruby_installed
  ignore_errors: yes

- name: Install Ruby if not already installed
  shell: rbenv install {{ ruby_version }}
  when: ruby_installed is failed

- name: Set Ruby as global version
  shell: rbenv global {{ ruby_version }}

- name: Check if bundler is installed
  shell: gem list bundler -v {{ bundler_version }} -i
  register: bundler_installed
  ignore_errors: yes

- name: Install bundler if not installed
  shell: gem install bundler -v {{ bundler_version }}
  args:
    chdir: "{{ app_dir }}"
  when: bundler_installed is failed

- name: Run rbenv rehash
  shell: rbenv rehash
