---
- name: Check if rbenv is installed
  shell: bash -lc "rbenv -v"
  register: rbenv_installed
  ignore_errors: yes

- name: Clone rbenv if not installed
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: '/home/ec2-user/.rbenv'
  when: rbenv_installed is failed

- name: Clone ruby-build if not installed
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: '/home/ec2-user/.rbenv/plugins/ruby-build'
  when: rbenv_installed is failed 

- name: Check if Ruby is already installed with rbenv
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  ignore_errors: yes

- name: Install Ruby if not already installed
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: ruby_installed is failed

- name: Set Ruby as global version and rehash
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"

- name: Check if bundler is installed
  shell: bash -lc "gem list bundler -v {{ bundler_version }} -i"
  register: bundler_installed
  ignore_errors: yes

- name: Install bundler if not installed
  shell: bash -lc "gem install bundler -v {{ bundler_version }}"
  args:
    chdir: "{{ app_dir }}"
  when: bundler_installed is failed

- name: Run rbenv rehash
  shell: bash -lc "rbenv rehash"
